name: Pull Request
on:
  pull_request:
    branches: [ master ]

jobs:

  checkstyle:
    name: Check project styling (Android lint, Detekt)
    runs-on: ubuntu-latest
    steps:
      - name: SCM
        uses: actions/checkout@v2

      - name: Android lint
        run: ./gradlew lint

      - name: Detekt
        run: ./gradlew detekt

      - uses: actions/upload-artifact@v2
         with:
          name: lint-report.html
          path: app/build/reports/lint-results.html

      - uses: actions/upload-artifact@v2
          with:
            name: detekt.html
            path: build/reports/detekt.html

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: SCM
        uses: actions/checkout@v2

      - name: Test
        run: ./gradlew testDebugUnitTest

  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - name: SCM
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Gradle
        run: ./gradlew build --stacktrace
